info:
  version: ${project.version}
  stage: dev

server:
  port: ${server.port}

management:
  security:
    flag: false
  server:
    port: ${management.port}
  metrics:
    export:
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: ${project.name}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    hikari:
      maximum-pool-size: 3
  flyway:
    table: schema_version
    schemas: ${db.schema}
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fistful-magista-3
      enable-auto-commit: false
      max-poll-records: 100
      properties:
        max.poll.interval.ms: 60000
        session.timeout.ms: 60000
    listener:
      concurrency: 7

kafka:
  topic:
    deposit:
      name: mg-events-ff-deposit
      listener:
        enabled: false

    withdrawal:
      name: mg-events-ff-withdrawal
      listener:
        enabled: false
    source:
      name: mg-events-ff-source
      listener:
        enabled: false
